-- MySQL Script generated by MySQL Workbench
-- Tue May  5 03:40:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`STAFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAFF` (
  `Staff_AMKA` VARCHAR(11) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Hiring_Date` DATE NOT NULL,
  `Staff_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Staff_AMKA`),
  CONSTRAINT `chk_staff_age` CHECK (`Age` >= 18 AND `Age` <=70),
  CONSTRAINT `chk_staff_type` CHECK (`Staff_Type` IN ('Ιατρός', 'Νοσηλευτής', 'Διοικητικός'))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `License_Number` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  `Rank` VARCHAR(45) NOT NULL,
  `Staff_AMKA` VARCHAR(11) NOT NULL,
  `Supervisor_AMKA` VARCHAR(11) NULL,
  PRIMARY KEY (`Staff_AMKA`),
  INDEX `fk_Doctor_STAFF_idx` (`Staff_AMKA` ASC) VISIBLE,
  INDEX `fk_Doctor_Doctor1_idx` (`Supervisor_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_STAFF`
    FOREIGN KEY (`Staff_AMKA`)
    REFERENCES `mydb`.`STAFF` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Doctor1`
    FOREIGN KEY (`Supervisor_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_doctor_rank` CHECK (`Rank` IN ('Ειδικευόμενος', 'Επιμελητής Β', 'Επιμελητής Α', 'Διευθυντής')),
  CONSTRAINT `chk_supervisor_rules` CHECK (
    (`Rank` = 'Ειδικευόμενος' AND `Supervisor_AMKA` IS NOT NULL) OR
    (`Rank` = 'Διευθυντής' AND `Supervisor_AMKA` IS NULL) OR
    (`Rank` NOT IN ('Ειδικευόμενος', 'Διευθυντής'))
  )
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department_Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Num_of_Beds` INT NOT NULL,
  `Floor` INT NOT NULL,
  `Building` VARCHAR(45) NOT NULL,
  `DirectedBy` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Department_Name`),
  INDEX `fk_Department_Doctor1_idx` (`DirectedBy` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Doctor1`
    FOREIGN KEY (`DirectedBy`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_dept_name` CHECK (`Department_Name` IN ('Καρδιολογία', 'Χειρουργική', 'ΜΕΘ', 'Επείγοντα', 'Νευρολογία', 'Παθολογία', 'Ορθοπεδική', 'Ουρολογία', 'Οφθαλμολογία', 'ΩΡΛ', 'Πνευμονολογία', 'Γαστρεντερολογία', 'Νεφρολογία', 'Αιματολογία', 'Ογκολογία')),
  CONSTRAINT `chk_num_of_beds` CHECK (`Num_of_Beds` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nurse` (
  `Nurse_Rank` VARCHAR(45) NOT NULL,
  `Staff_AMKA` VARCHAR(11) NOT NULL,
  `NurseBelongsDepartment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Staff_AMKA`),
  INDEX `fk_Nurse_STAFF1_idx` (`Staff_AMKA` ASC) VISIBLE,
  INDEX `fk_Nurse_Department1_idx` (`NurseBelongsDepartment` ASC) VISIBLE,
  CONSTRAINT `fk_Nurse_STAFF1`
    FOREIGN KEY (`Staff_AMKA`)
    REFERENCES `mydb`.`STAFF` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nurse_Department1`
    FOREIGN KEY (`NurseBelongsDepartment`)
    REFERENCES `mydb`.`Department` (`Department_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_nurse_rank` CHECK (`Nurse_Rank` IN ('Βοηθός Νοσηλευτή', 'Νοσηλευτής', 'Προϊστάμενος'))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Management` (
`Role` VARCHAR(45) NOT NULL,
`Office` VARCHAR(45) NOT NULL,
`Staff_AMKA` VARCHAR(11) NOT NULL,
`ManagerBelongsDepartment` VARCHAR(45) NOT NULL,
PRIMARY KEY (`Staff_AMKA`),
INDEX `fk_Management_STAFF1_idx` (`Staff_AMKA` ASC) VISIBLE,
INDEX `fk_Management_Department1_idx` (`ManagerBelongsDepartment` ASC) VISIBLE,
CONSTRAINT `fk_Management_STAFF1`
  FOREIGN KEY (`Staff_AMKA`)
  REFERENCES `mydb`.`STAFF` (`Staff_AMKA`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
CONSTRAINT `fk_Management_Department1`
  FOREIGN KEY (`ManagerBelongsDepartment`)
  REFERENCES `mydb`.`Department` (`Department_Name`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
CONSTRAINT `chk_management_role` CHECK (`Role` IN ('Γραμματέας', 'Λογιστής', 'Ανθρώπινο Δυναμικό'))  
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Belongs_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Belongs_Doctor` (
  `Doctor_AMKA` VARCHAR(11) NOT NULL,
  `Department_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Doctor_AMKA`, `Department_Name`),
  INDEX `fk_Doctor_has_Department_Department1_idx` (`Department_Name` ASC) VISIBLE,
  INDEX `fk_Doctor_has_Department_Doctor1_idx` (`Doctor_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_has_Department_Doctor1`
    FOREIGN KEY (`Doctor_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Department_Department1`
    FOREIGN KEY (`Department_Name`)
    REFERENCES `mydb`.`Department` (`Department_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bed` (
  `Department_Name` VARCHAR(45) NOT NULL,
  `Bed_Number` INT NOT NULL,
  `Bed_Type` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Department_Name`, `Bed_Number`),
  CONSTRAINT `fk_Bed_Department1`
    FOREIGN KEY (`Department_Name`)
    REFERENCES `mydb`.`Department` (`Department_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_bed_number` CHECK (`Bed_Number` > 0),
  CONSTRAINT `chk_bed_type` CHECK (`Bed_Type` IN ('ΜΕΘ', 'Μονόκλινο', 'Πολύκλινο')),
  CONSTRAINT `chk_bed_status` CHECK (`Status` IN ('Διαθέσιμη', 'Κατειλημμένη', 'Υπό Συντήρηση'))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance` (
  `Provider` VARCHAR(45) NOT NULL,
  `Provider_Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`Provider`),
CONSTRAINT `chk_provider_name`CHECK (`Provider` IN ('ΕΦΚΑ', 'ΕΟΠΥΥ', 'Ιδιωτική Ασφάλεια', 'Ανασφάλιστος'))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `Patient_AMKA` VARCHAR(11) NOT NULL,
  `Patient_First_Name` VARCHAR(45) NOT NULL,
  `Patient_Last_Name` VARCHAR(45) NOT NULL,
  `Patient_Father_Name` VARCHAR(45) NOT NULL,
  `Patient_Age` INT NOT NULL,
  `Age_Month` INT NULL,
  `Patient_Gender` VARCHAR(45) NOT NULL,
  `Patient_Weight` DECIMAL(10,2) NOT NULL,
  `Patient_Height` DECIMAL(10,2) NOT NULL,
  `Patient_Address` VARCHAR(45) NOT NULL,
  `Patient_Phone_Number` VARCHAR(45) NOT NULL,
  `Patient_Email` VARCHAR(45) NOT NULL,
  `Patient_Profession` VARCHAR(45) NOT NULL,
  `Patient_Nationality` VARCHAR(45) NOT NULL,
  `Emergency_Contact` VARCHAR(45) NOT NULL,
  `Insurance_Provider` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Patient_AMKA`),
  INDEX `fk_Patient_Insurance1_idx` (`Insurance_Provider` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Insurance1`
    FOREIGN KEY (`Insurance_Provider`)
    REFERENCES `mydb`.`Insurance` (`Provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_age` CHECK ((`Patient_Age` > 0 AND (Age_Month IS NULL OR Age_Month = 0)) OR (`Patient_Age` = 0 AND `Age_Month` >= 0)),
  CONSTRAINT `chk_gender` CHECK (`Patient_Gender` IN ('Άρρεν', 'Θήλυ')),
  CONSTRAINT `chk_weight` CHECK (`Patient_Weight` > 0),
  CONSTRAINT `chk_height` CHECK (`Patient_Height` > 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Triage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Triage` (
  `Triage_ID` INT NOT NULL,
  `Symptoms` VARCHAR(45) NOT NULL,
  `Urgency_Level` INT NOT NULL,
  `Arrival_DateTime` DATETIME NOT NULL,
  `Waiting_Minutes` INT NULL,
  `Patient_AMKA` VARCHAR(11) NOT NULL,
  `Nurse_AMKA` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Triage_ID`),
  INDEX `fk_Triage_Patient1_idx` (`Patient_AMKA` ASC) VISIBLE,
  INDEX `fk_Triage_Nurse1_idx` (`Nurse_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Triage_Patient1`
    FOREIGN KEY (`Patient_AMKA`)
    REFERENCES `mydb`.`Patient` (`Patient_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Triage_Nurse1`
    FOREIGN KEY (`Nurse_AMKA`)
    REFERENCES `mydb`.`Nurse` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_triage_id` CHECK (`Triage_ID` >= 0),
  CONSTRAINT `chk_urgency_level` CHECK (`Urgency_Level` IN (1, 2, 3, 4, 5)),
  CONSTRAINT `chk_waiting_minutes` CHECK (`Waiting_Minutes` IS NULL OR `Waiting_Minutes` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KEN` (
  `KEN_Code` VARCHAR(10) NOT NULL,
  `KEN_Cost` DECIMAL(10,2) NOT NULL,
  `MDN` INT NOT NULL,
  PRIMARY KEY (`KEN_Code`),
  CONSTRAINT `chk_KEN_cost` CHECK (`KEN_Cost` >= 0),
  CONSTRAINT `chk_MDN` CHECK (`MDN` > 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnosis` (
  `ICD_10_Code` VARCHAR(10) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ICD_10_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admission` (
  `AdmissionID` INT NOT NULL,
  `Admission_Date` DATE NOT NULL,
  `Release_Date` DATE NULL,
  `Total_Cost` DECIMAL(10,2) NULL,
  `Department_Name` VARCHAR(45) NOT NULL,
  `Bed_Number` INT NOT NULL,
  `Patient_AMKA` VARCHAR(11) NOT NULL,
  `Triage_ID` INT NOT NULL,
  `KEN_Code` VARCHAR(10) NOT NULL,
  `Admission_Diagnosis_ICD_10_Code` VARCHAR(10) NOT NULL,
  `Release_Diagnosis_ICD_10_Code` VARCHAR(10) NULL,
  PRIMARY KEY (`AdmissionID`),
  INDEX `fk_Admission_Bed1_idx` (`Department_Name` ASC, `Bed_Number` ASC) VISIBLE,
  INDEX `fk_Admission_Patient1_idx` (`Patient_AMKA` ASC) VISIBLE,
  INDEX `fk_Admission_Triage1_idx` (`Triage_ID` ASC) VISIBLE,
  INDEX `fk_Admission_KEN1_idx` (`KEN_Code` ASC) VISIBLE,
  INDEX `fk_Admission_Diagnosis1_idx` (`Admission_Diagnosis_ICD_10_Code` ASC) VISIBLE,
  INDEX `fk_Admission_Diagnosis2_idx` (`Release_Diagnosis_ICD_10_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Admission_Bed1`
    FOREIGN KEY (`Department_Name` , `Bed_Number`)
    REFERENCES `mydb`.`Bed` (`Department_Name` , `Bed_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admission_Patient1`
    FOREIGN KEY (`Patient_AMKA`)
    REFERENCES `mydb`.`Patient` (`Patient_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admission_Triage1`
    FOREIGN KEY (`Triage_ID`)
    REFERENCES `mydb`.`Triage` (`Triage_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admission_KEN1`
    FOREIGN KEY (`KEN_Code`)
    REFERENCES `mydb`.`KEN` (`KEN_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admission_Diagnosis1`
    FOREIGN KEY (`Admission_Diagnosis_ICD_10_Code`)
    REFERENCES `mydb`.`Diagnosis` (`ICD_10_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admission_Diagnosis2`
    FOREIGN KEY (`Release_Diagnosis_ICD_10_Code`)
    REFERENCES `mydb`.`Diagnosis` (`ICD_10_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_admission_id` CHECK (`AdmissionID` >= 0),
  CONSTRAINT `chk_total_cost` CHECK (`Total_Cost` >= 0),
  CONSTRAINT `chk_admission_time_logic` CHECK ((`Release_Date` IS NULL) OR (`Admission_Date` <= `Release_Date`))

)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shift` (
  `Shift_Date` DATE NOT NULL,
  `Shift_Type` VARCHAR(45) NOT NULL,
  `Start_Time` DATETIME NOT NULL,
  `End_Time` DATETIME NOT NULL,
  `Department_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Shift_Date`, `Shift_Type`, `Department_Name`),
  INDEX `fk_Shift_Department1_idx` (`Department_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Shift_Department1`
    FOREIGN KEY (`Department_Name`)
    REFERENCES `mydb`.`Department` (`Department_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_shift_type` CHECK (`Shift_Type` IN ('Πρωινή', 'Απογευματινή', 'Νυχτερινή')),
  CONSTRAINT `chk_shift_time_logic` CHECK (`End_Time` >= `Start_Time`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shift_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shift_Staff` (
  `Shift_Date` DATE NOT NULL,
  `Shift_Type` VARCHAR(45) NOT NULL,
  `Department_Name` VARCHAR(45) NOT NULL,
  `Staff_AMKA` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Shift_Date`, `Shift_Type`, `Department_Name`, `Staff_AMKA`),
  INDEX `fk_Shift_has_STAFF_STAFF1_idx` (`Staff_AMKA` ASC) VISIBLE,
  INDEX `fk_Shift_has_STAFF_Shift1_idx` (`Shift_Date` ASC, `Shift_Type` ASC, `Department_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Shift_has_STAFF_Shift1`
    FOREIGN KEY (`Shift_Date` , `Shift_Type` , `Department_Name`)
    REFERENCES `mydb`.`Shift` (`Shift_Date` , `Shift_Type` , `Department_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shift_has_STAFF_STAFF1`
    FOREIGN KEY (`Staff_AMKA`)
    REFERENCES `mydb`.`STAFF` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exam` (
  `Exam_Code` INT NOT NULL,
  `Exam_Type` VARCHAR(45) NOT NULL,
  `Exam_Date` DATE NOT NULL,
  `Exam_Result` VARCHAR(45) NOT NULL,
  `Measurement_Unit` VARCHAR(45) NULL,
  `Exam_Cost` DECIMAL(10,2) NOT NULL,
  `AdmissionID` INT NOT NULL,
  `Doctor_AMKA` VARCHAR(11) NOT NULL,
  INDEX `fk_Exam_Admission1_idx` (`AdmissionID` ASC) VISIBLE,
  INDEX `fk_Exam_Doctor1_idx` (`Doctor_AMKA` ASC) VISIBLE,
  PRIMARY KEY (`Exam_Code`),
  CONSTRAINT `fk_Exam_Admission1`
    FOREIGN KEY (`AdmissionID`)
    REFERENCES `mydb`.`Admission` (`AdmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam_Doctor1`
    FOREIGN KEY (`Doctor_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_exam_code` CHECK (`Exam_Code` >= 0),
  CONSTRAINT `chk_exam_cost` CHECK (`Exam_Cost` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operating_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operating_Room` (
  `Room_Code` INT NOT NULL,
  `Room_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Room_Code`),
  CONSTRAINT `chk_room_code` CHECK (`Room_Code` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Action` (
  `Action_Code` INT NOT NULL,
  `Action_Name` VARCHAR(400) NOT NULL,
  `Action_Type` VARCHAR(45) NOT NULL,
  `Action_Start` DATETIME NOT NULL,
  `Action_Duration` INT NOT NULL,     -- in minutes
  `Action_Cost` DECIMAL(10,2) NOT NULL,
  `AdmissionID` INT NOT NULL,
  `Operating_Room_Code` INT NOT NULL,
  PRIMARY KEY (`Action_Code`),
  INDEX `fk_Medical_Action_Admission1_idx` (`AdmissionID` ASC) VISIBLE,
  INDEX `fk_Medical_Action_Operating_Room1_idx` (`Operating_Room_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Medical_Action_Admission1`
    FOREIGN KEY (`AdmissionID`)
    REFERENCES `mydb`.`Admission` (`AdmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Action_Operating_Room1`
    FOREIGN KEY (`Operating_Room_Code`)
    REFERENCES `mydb`.`Operating_Room` (`Room_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_action_code` CHECK (`Action_Code` >= 0),
  CONSTRAINT `chk_action_type` CHECK (`Action_Type` IN ('Χειρουργική', 'Διαγνωστική', 'Θεραπευτική')),
  CONSTRAINT `chk_action_cost` CHECK (`Action_Cost` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Surgery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Surgery` (
  `Surgery_Type` VARCHAR(45) NOT NULL,
  `Action_Code` INT NOT NULL,
  `Main_Surgeon_AMKA` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Action_Code`),
  INDEX `fk_Surgery_Medical_Action1_idx` (`Action_Code` ASC) VISIBLE,
  INDEX `fk_Surgery_Doctor1_idx` (`Main_Surgeon_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Surgery_Medical_Action1`
    FOREIGN KEY (`Action_Code`)
    REFERENCES `mydb`.`Medical_Action` (`Action_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Surgery_Doctor1`
    FOREIGN KEY (`Main_Surgeon_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_surgery_action_code` CHECK (`Action_Code` >= 0)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Surgery_Assistant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Surgery_Assistant` (
  `Surgery_Action_Code` INT NOT NULL,
  `Assistant_AMKA` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Surgery_Action_Code`, `Assistant_AMKA`),
  INDEX `fk_Surgery_has_STAFF_STAFF1_idx` (`Assistant_AMKA` ASC) VISIBLE,
  INDEX `fk_Surgery_has_STAFF_Surgery1_idx` (`Surgery_Action_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Surgery_has_STAFF_Surgery1`
    FOREIGN KEY (`Surgery_Action_Code`)
    REFERENCES `mydb`.`Surgery` (`Action_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Surgery_has_STAFF_STAFF1`
    FOREIGN KEY (`Assistant_AMKA`)
    REFERENCES `mydb`.`STAFF` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation` (
  `Nursing_Quality` INT NOT NULL,
  `Cleanliness` INT NOT NULL,
  `Food` INT NOT NULL,
  `Overall_Experience` INT NOT NULL,
  `AdmissionID` INT NOT NULL,
  PRIMARY KEY (`AdmissionID`),
  INDEX `fk_Evaluation_Admission1_idx` (`AdmissionID` ASC) VISIBLE,
  CONSTRAINT `fk_Evaluation_Admission1`
    FOREIGN KEY (`AdmissionID`)
    REFERENCES `mydb`.`Admission` (`AdmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  -- 1 : Very Bad , 2 : Bad , 3 : Acceptable , 4 : Good , 5 : Excellent
  CONSTRAINT `chk_nursing_quality` CHECK (`Nursing_Quality` IN (1, 2, 3, 4, 5)),
  CONSTRAINT `chk_cleanliness` CHECK (`Cleanliness` IN (1, 2, 3, 4, 5)),
  CONSTRAINT `chk_food` CHECK (`Food` IN (1, 2, 3, 4, 5)),
  CONSTRAINT `chk_overall_experience` CHECK (`Overall_Experience` IN (1, 2, 3, 4, 5))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor_Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor_Evaluation` (
  `AdmissionID` INT NOT NULL,
  `Doctor_AMKA` VARCHAR(11) NOT NULL,
  `Doctor_Quality` INT NOT NULL,
  PRIMARY KEY (`AdmissionID`, `Doctor_AMKA`),
  INDEX `fk_Doctor_Evaluation_Doctor1_idx` (`Doctor_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Evaluation_Evaluation1`
    FOREIGN KEY (`AdmissionID`)
    REFERENCES `mydb`.`Evaluation` (`AdmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Evaluation_Doctor1`
    FOREIGN KEY (`Doctor_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  -- 1 : Very Bad , 2 : Bad , 3 : Acceptable , 4 : Good , 5 : Excellent
  CONSTRAINT `chk_doctor_quality` CHECK (`Doctor_Quality` IN (1, 2, 3, 4, 5))
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicine` (
  `EMA_Code` VARCHAR(45) NOT NULL,
  `Medicine_Name` VARCHAR(200) NULL,
  PRIMARY KEY (`EMA_Code`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prescription` (
  `Prescription_ID` INT NOT NULL,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Dosage` INT NOT NULL,
  `Frequency` INT NOT NULL,
  `Doctor_AMKA` VARCHAR(11) NOT NULL,
  `EMA_Code` VARCHAR(45) NOT NULL,
  `AdmissionID` INT NOT NULL,
  PRIMARY KEY (`Prescription_ID`),
  INDEX `fk_Prescription_Doctor1_idx` (`Doctor_AMKA` ASC) VISIBLE,
  INDEX `fk_Prescription_Medicine1_idx` (`EMA_Code` ASC) VISIBLE,
  INDEX `fk_Prescription_Admission1_idx` (`AdmissionID` ASC) VISIBLE,
  CONSTRAINT `fk_Prescription_Doctor1`
    FOREIGN KEY (`Doctor_AMKA`)
    REFERENCES `mydb`.`Doctor` (`Staff_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Medicine1`
    FOREIGN KEY (`EMA_Code`)
    REFERENCES `mydb`.`Medicine` (`EMA_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prescription_Admission1`
    FOREIGN KEY (`AdmissionID`)
    REFERENCES `mydb`.`Admission` (`AdmissionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_prescription_id` CHECK (`Prescription_ID` >= 0),
  CONSTRAINT `chk_prescription_time_logic` CHECK (`Start_Date` <= `End_Date`),
  CONSTRAINT `chk_dosage` CHECK (`Dosage` >= 0),
  CONSTRAINT `chk_frequency` CHECK (`Frequency` >= 0),
  CONSTRAINT `unique_prescription_combo` UNIQUE (`Doctor_AMKA`, `AdmissionID`, `EMA_Code`, `Start_Date`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Active_Substance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Active_Substance` (
  `Substance_ID` VARCHAR(45) NOT NULL,
  `Substance_Name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Substance_ID`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicine_Composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicine_Composition` (
  `EMA_Code` VARCHAR(45) NOT NULL,
  `Substance_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EMA_Code`, `Substance_ID`),
  INDEX `fk_Medicine_has_Active_Substance_Active_Substance1_idx` (`Substance_ID` ASC) VISIBLE,
  INDEX `fk_Medicine_has_Active_Substance_Medicine1_idx` (`EMA_Code` ASC) VISIBLE,
  CONSTRAINT `fk_Medicine_has_Active_Substance_Medicine1`
    FOREIGN KEY (`EMA_Code`)
    REFERENCES `mydb`.`Medicine` (`EMA_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicine_has_Active_Substance_Active_Substance1`
    FOREIGN KEY (`Substance_ID`)
    REFERENCES `mydb`.`Active_Substance` (`Substance_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient_Allergy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient_Allergy` (
  `Patient_AMKA` VARCHAR(11) NOT NULL,
  `Substance_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Patient_AMKA`, `Substance_ID`),
  INDEX `fk_Patient_has_Active_Substance_Active_Substance1_idx` (`Substance_ID` ASC) VISIBLE,
  INDEX `fk_Patient_has_Active_Substance_Patient1_idx` (`Patient_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_has_Active_Substance_Patient1`
    FOREIGN KEY (`Patient_AMKA`)
    REFERENCES `mydb`.`Patient` (`Patient_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_has_Active_Substance_Active_Substance1`
    FOREIGN KEY (`Substance_ID`)
    REFERENCES `mydb`.`Active_Substance` (`Substance_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entity_Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entity_Image` (
  `Image_ID` INT NOT NULL AUTO_INCREMENT,
  `Entity_Type` VARCHAR(45) NOT NULL,
  `Entity_Key` VARCHAR(100) NOT NULL,
  `Image_URL` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Image_ID`),
  CONSTRAINT `chk_entity_type` CHECK (`Entity_Type` IN (
    'Department', 'Doctor', 'Nurse', 'Management', 'Patient',
    'Medicine', 'Operating_Room', 'Bed', 'Medical_Action',
    'Exam', 'Surgery', 'Diagnosis', 'KEN'
  ))
)ENGINE = InnoDB;



DELIMITER //
CREATE PROCEDURE `circular_supervision` (IN supervisor_AMKA VARCHAR(11), IN supervisee_AMKA VARCHAR(11))
BEGIN
    DECLARE next_supervisor_AMKA VARCHAR(11);

    SELECT Supervisor_AMKA
    INTO next_supervisor_AMKA
    FROM Doctor
    WHERE Staff_AMKA = supervisor_AMKA;

    WHILE ((next_supervisor_amka IS NOT NULL) AND (next_supervisor_AMKA <> supervisee_AMKA))DO
        SELECT Supervisor_AMKA
        INTO next_supervisor_AMKA
        FROM Doctor
        WHERE Staff_AMKA = next_supervisor_AMKA;
    END WHILE;

    IF (next_supervisor_AMKA = supervisee_AMKA) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Κυκλική αλυσίδα εποπτείας.';
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER `ins_doctor` BEFORE INSERT ON `Doctor` FOR EACH ROW
BEGIN
    CALL circular_supervision(new.Supervisor_AMKA, new.Staff_AMKA);
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `upd_doctor` BEFORE UPDATE ON `Doctor` FOR EACH ROW
BEGIN
    CALL circular_supervision(new.Supervisor_AMKA, new.Staff_AMKA);
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `ins_admission_cost_calculation` BEFORE INSERT ON `Admission` FOR EACH ROW
BEGIN
    DECLARE ken_cost DECIMAL(10,2);
    DECLARE mdn INT;
    DECLARE days_stayed INT;
    DECLARE daily_extra_charge DECIMAL(10,2);

    IF NEW.Release_Date IS NOT NULL THEN

        SELECT KEN_Cost, MDN
        INTO ken_cost, mdn
        FROM KEN
        WHERE KEN_Code = NEW.KEN_Code;

        SET days_stayed = DATEDIFF(NEW.Release_Date, NEW.Admission_Date);

        IF days_stayed <= mdn THEN
            SET NEW.Total_Cost = ken_cost;
        ELSE
            SET daily_extra_charge = ken_cost / mdn;
            SET NEW.Total_Cost = ken_cost + ((days_stayed - mdn) * daily_extra_charge);
        END IF;

    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `upd_admission_cost_calculation` BEFORE UPDATE ON `Admission` FOR EACH ROW
BEGIN
    DECLARE ken_cost DECIMAL(10,2);
    DECLARE mdn INT;
    DECLARE days_stayed INT;
    DECLARE daily_extra_charge DECIMAL(10,2);

    IF NEW.Release_Date IS NOT NULL THEN

        SELECT KEN_Cost, MDN
        INTO ken_cost, mdn
        FROM KEN
        WHERE KEN_Code = NEW.KEN_Code;

        SET days_stayed = DATEDIFF(NEW.Release_Date, NEW.Admission_Date);

        IF days_stayed <= mdn THEN
            SET NEW.Total_Cost = ken_cost;
        ELSE
            SET daily_extra_charge = ken_cost / mdn;
            SET NEW.Total_Cost = ken_cost + ((days_stayed - mdn) * daily_extra_charge);
        END IF;

    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `surgery_constraints` (IN new_action_code INT, IN new_main_surgeon_amka VARCHAR(11))
BEGIN
    DECLARE room_code INT;
    DECLARE new_start_time DATETIME;
    DECLARE new_surgery_duration INT;
    DECLARE new_end_time DATETIME;

    SELECT Operating_Room_Code, Action_Start, Action_Duration
    INTO room_code, new_start_time, new_surgery_duration
    FROM Medical_Action
    WHERE Action_Code = new_action_code;

    SET new_end_time = DATE_ADD(new_start_time, INTERVAL new_surgery_duration MINUTE);

    IF EXISTS(
      SELECT 1
      FROM Medical_Action
      WHERE Operating_Room_Code = room_code
        AND Action_Code <> new_action_code
        AND (
          (new_start_time >= Action_Start AND new_start_time <= DATE_ADD(Action_Start, INTERVAL Action_Duration MINUTE)) 
          OR (new_end_time >= Action_Start AND new_end_time <= DATE_ADD(Action_Start, INTERVAL Action_Duration MINUTE))
          OR (new_start_time <= Action_Start AND new_end_time >= DATE_ADD(Action_Start, INTERVAL Action_Duration MINUTE))
        )
    ) THEN 
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Κατειλλημένος χώρος επέμβασης.';
    END IF;

    IF EXISTS(
      SELECT 1
      FROM Surgery s
      INNER JOIN Medical_Action ma ON ma.Action_Code = s.Action_Code
      WHERE s.Main_Surgeon_AMKA = new_main_surgeon_amka
        AND s.Action_Code <> new_Action_Code
        AND (
          (new_start_time >= ma.Action_Start AND new_start_time <= DATE_ADD(ma.Action_Start, INTERVAL ma.Action_Duration MINUTE)) 
          OR (new_end_time >= ma.Action_Start AND new_end_time <= DATE_ADD(ma.Action_Start, INTERVAL ma.Action_Duration MINUTE))
          OR (new_start_time <= ma.Action_Start AND new_end_time >= DATE_ADD(ma.Action_Start, INTERVAL ma.Action_Duration MINUTE))
        )
    ) THEN 
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Κατειλλημένος βασικός χειρουργός.';
    END IF;

END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `ins_surgery` BEFORE INSERT ON `Surgery` FOR EACH ROW
BEGIN
    CALL surgery_constraints(new.Action_Code, new.Main_Surgeon_AMKA);
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `upd_surgery` BEFORE UPDATE ON `Surgery` FOR EACH ROW
BEGIN
    CALL surgery_constraints(new.Action_Code, new.Main_Surgeon_AMKA);
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER ins_prescription_allergy_check BEFORE INSERT ON Prescription FOR EACH ROW
BEGIN
    IF EXISTS(
      SELECT 1
      FROM Medicine_Composition
      JOIN Patient_Allergy ON Medicine_Composition.Substance_ID = Patient_Allergy.Substance_ID
      JOIN Admission ON Admission.AdmissionID = new.AdmissionID
      WHERE Medicine_Composition.EMA_Code = new.EMA_Code
        AND Patient_Allergy.Patient_AMKA = Admission.Patient_AMKA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ο ασθενής έχει αλλεργία σε δραστική ουσία του συγκεκριμένου φαρμάκου.';
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER upd_prescription_allergy_check BEFORE UPDATE ON Prescription FOR EACH ROW
BEGIN
    IF EXISTS(
      SELECT 1
      FROM Medicine_Composition
      JOIN Patient_Allergy ON Medicine_Composition.Substance_ID = Patient_Allergy.Substance_ID
      JOIN Admission ON Admission.AdmissionID = new.AdmissionID
      WHERE Medicine_Composition.EMA_Code = new.EMA_Code
        AND Patient_Allergy.Patient_AMKA = Admission.Patient_AMKA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ο ασθενής έχει αλλεργία σε δραστική ουσία του συγκεκριμένου φαρμάκου.';
    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER ins_evaluation_completed_admission BEFORE INSERT ON Evaluation FOR EACH ROW
BEGIN
    DECLARE release_date DATE;

    SELECT Release_Date 
    INTO release_date 
    FROM Admission
    WHERE AdmissionID = NEW.AdmissionID;

    IF release_date IS NULL THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Η νοσηλεία δεν έχει ολοκληρωθεί ακόμη.';
    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER upd_evaluation_completed_admission BEFORE UPDATE ON Evaluation FOR EACH ROW
BEGIN
    DECLARE release_date DATE;

    SELECT Release_Date 
    INTO release_date 
    FROM Admission
    WHERE AdmissionID = NEW.AdmissionID;

    IF release_date IS NULL THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Η νοσηλεία δεν έχει ολοκληρωθεί ακόμη.';
    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `ins_doctor_eval_prescribed` BEFORE INSERT ON Doctor_Evaluation
FOR EACH ROW
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM Prescription
        WHERE Prescription.AdmissionID = NEW.AdmissionID
          AND Prescription.Doctor_AMKA = NEW.Doctor_AMKA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ο ιατρός δεν συνταγογράφησε σε αυτή τη νοσηλεία.';
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER `upd_doctor_eval_prescribed` BEFORE UPDATE ON Doctor_Evaluation
FOR EACH ROW
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM Prescription
        WHERE Prescription.AdmissionID = NEW.AdmissionID
          AND Prescription.Doctor_AMKA = NEW.Doctor_AMKA
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Ο ιατρός δεν συνταγογράφησε σε αυτή τη νοσηλεία.';
    END IF;
END //
DELIMITER ;


-- ============================================
-- Trigger: Comprehensive shift staff constraints
-- Enforces: monthly limits, 8-hour rest, max 3 consecutive night shifts
-- ============================================
DELIMITER //
CREATE TRIGGER `chk_shift_staff_constraints` BEFORE INSERT ON `Shift_Staff` FOR EACH ROW
BEGIN
    DECLARE v_staff_type VARCHAR(45);
    DECLARE v_shift_count INT;
    DECLARE v_new_start DATETIME;
    DECLARE v_new_end DATETIME;
    DECLARE v_back INT DEFAULT 0;
    DECLARE v_fwd INT DEFAULT 0;

    -- Get staff type
    SELECT Staff_Type INTO v_staff_type
    FROM STAFF WHERE Staff_AMKA = NEW.Staff_AMKA;

    -- Get new shift start/end times
    SELECT Start_Time, End_Time
    INTO v_new_start, v_new_end
    FROM Shift
    WHERE Shift_Date = NEW.Shift_Date
      AND Shift_Type = NEW.Shift_Type
      AND Department_Name = NEW.Department_Name;

    -- ============================================
    -- 1. Monthly shift limits per staff type
    -- ============================================
    SELECT COUNT(*) INTO v_shift_count
    FROM Shift_Staff
    WHERE Staff_AMKA = NEW.Staff_AMKA
      AND MONTH(Shift_Date) = MONTH(NEW.Shift_Date)
      AND YEAR(Shift_Date) = YEAR(NEW.Shift_Date);

    IF v_staff_type = 'Ιατρός' AND v_shift_count >= 15 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Υπέρβαση ορίου: Ιατροί έως 15 βάρδιες/μήνα.';
    ELSEIF v_staff_type = 'Νοσηλευτής' AND v_shift_count >= 20 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Υπέρβαση ορίου: Νοσηλευτές έως 20 βάρδιες/μήνα.';
    ELSEIF v_staff_type = 'Διοικητικός' AND v_shift_count >= 25 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Υπέρβαση ορίου: Διοικητικοί έως 25 βάρδιες/μήνα.';
    END IF;

    -- ============================================
    -- 2. Minimum 8-hour rest between shifts
    -- ============================================
    IF v_new_start IS NOT NULL AND v_new_end IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM Shift_Staff ss
            JOIN Shift s ON ss.Shift_Date = s.Shift_Date
                        AND ss.Shift_Type = s.Shift_Type
                        AND ss.Department_Name = s.Department_Name
            WHERE ss.Staff_AMKA = NEW.Staff_AMKA
              AND NOT (ss.Shift_Date = NEW.Shift_Date
                       AND ss.Shift_Type = NEW.Shift_Type
                       AND ss.Department_Name = NEW.Department_Name)
              AND (
                  s.End_Time > DATE_SUB(v_new_start, INTERVAL 8 HOUR)
                  AND s.Start_Time < DATE_ADD(v_new_end, INTERVAL 8 HOUR)
              )
        ) THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Ελάχιστο 8ωρο ανάπαυσης μεταξύ διαδοχικών βαρδιών.';
        END IF;
    END IF;

    -- ============================================
    -- 3. Max 3 consecutive night shifts
    -- ============================================
    IF NEW.Shift_Type = 'Νυχτερινή' THEN
        -- Count consecutive nights before this date
        IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                   AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_SUB(NEW.Shift_Date, INTERVAL 1 DAY)) THEN
            SET v_back = 1;
            IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                       AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_SUB(NEW.Shift_Date, INTERVAL 2 DAY)) THEN
                SET v_back = 2;
                IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                           AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_SUB(NEW.Shift_Date, INTERVAL 3 DAY)) THEN
                    SET v_back = 3;
                END IF;
            END IF;
        END IF;

        -- Count consecutive nights after this date
        IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                   AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_ADD(NEW.Shift_Date, INTERVAL 1 DAY)) THEN
            SET v_fwd = 1;
            IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                       AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_ADD(NEW.Shift_Date, INTERVAL 2 DAY)) THEN
                SET v_fwd = 2;
                IF EXISTS (SELECT 1 FROM Shift_Staff WHERE Staff_AMKA = NEW.Staff_AMKA
                           AND Shift_Type = 'Νυχτερινή' AND Shift_Date = DATE_ADD(NEW.Shift_Date, INTERVAL 3 DAY)) THEN
                    SET v_fwd = 3;
                END IF;
            END IF;
        END IF;

        -- Total chain = backwards + 1 (new) + forwards; must not exceed 3
        IF (v_back + 1 + v_fwd) > 3 THEN
            SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Υπέρβαση ορίου 3 συνεχόμενων νυχτερινών βαρδιών.';
        END IF;
    END IF;
END //
DELIMITER ;


-- ============================================
-- Stored Procedure: Validate shift staffing levels
-- Checks minimum personnel (3 doctors, 6 nurses, 2 admin)
-- and supervisor presence when residents are assigned
-- Call after inserting all staff for a shift:
--   CALL validate_shift_staffing('2026-03-01', 'Πρωινή', 'Καρδιολογία');
-- ============================================
DELIMITER //
CREATE PROCEDURE `validate_shift_staffing` (
    IN p_shift_date DATE,
    IN p_shift_type VARCHAR(45),
    IN p_department_name VARCHAR(45)
)
BEGIN
    DECLARE v_doctors INT DEFAULT 0;
    DECLARE v_nurses INT DEFAULT 0;
    DECLARE v_admin INT DEFAULT 0;
    DECLARE v_has_resident INT DEFAULT 0;
    DECLARE v_has_supervisor INT DEFAULT 0;

    SELECT COUNT(*) INTO v_doctors
    FROM Shift_Staff ss
    JOIN STAFF s ON ss.Staff_AMKA = s.Staff_AMKA
    WHERE ss.Shift_Date = p_shift_date
      AND ss.Shift_Type = p_shift_type
      AND ss.Department_Name = p_department_name
      AND s.Staff_Type = 'Ιατρός';

    SELECT COUNT(*) INTO v_nurses
    FROM Shift_Staff ss
    JOIN STAFF s ON ss.Staff_AMKA = s.Staff_AMKA
    WHERE ss.Shift_Date = p_shift_date
      AND ss.Shift_Type = p_shift_type
      AND ss.Department_Name = p_department_name
      AND s.Staff_Type = 'Νοσηλευτής';

    SELECT COUNT(*) INTO v_admin
    FROM Shift_Staff ss
    JOIN STAFF s ON ss.Staff_AMKA = s.Staff_AMKA
    WHERE ss.Shift_Date = p_shift_date
      AND ss.Shift_Type = p_shift_type
      AND ss.Department_Name = p_department_name
      AND s.Staff_Type = 'Διοικητικός';

    SELECT COUNT(*) INTO v_has_resident
    FROM Shift_Staff ss
    JOIN Doctor d ON ss.Staff_AMKA = d.Staff_AMKA
    WHERE ss.Shift_Date = p_shift_date
      AND ss.Shift_Type = p_shift_type
      AND ss.Department_Name = p_department_name
      AND d.`Rank` = 'Ειδικευόμενος';

    SELECT COUNT(*) INTO v_has_supervisor
    FROM Shift_Staff ss
    JOIN Doctor d ON ss.Staff_AMKA = d.Staff_AMKA
    WHERE ss.Shift_Date = p_shift_date
      AND ss.Shift_Type = p_shift_type
      AND ss.Department_Name = p_department_name
      AND d.`Rank` IN ('Επιμελητής Α', 'Διευθυντής');

    IF v_doctors < 3 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Η βάρδια απαιτεί τουλάχιστον 3 ιατρούς.';
    END IF;

    IF v_nurses < 6 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Η βάρδια απαιτεί τουλάχιστον 6 νοσηλευτές.';
    END IF;

    IF v_admin < 2 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Η βάρδια απαιτεί τουλάχιστον 2 διοικητικούς υπαλλήλους.';
    END IF;

    IF v_has_resident > 0 AND v_has_supervisor = 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Σε βάρδια με ειδικευόμενο πρέπει να παρίσταται Επιμελητής Α ή Διευθυντής.';
    END IF;
END //
DELIMITER ;


DELIMITER //
CREATE TRIGGER `chk_delete_senior_from_shift` BEFORE DELETE ON `Shift_Staff` FOR EACH ROW
BEGIN
    DECLARE v_rank VARCHAR(45);
    DECLARE has_resident INT DEFAULT 0;

    SELECT `Rank` INTO v_rank
    FROM Doctor
    WHERE Staff_AMKA = OLD.Staff_AMKA;

    IF v_rank IN ('Επιμελητής Α', 'Διευθυντής') THEN

        SELECT COUNT(*) INTO has_resident
        FROM Shift_Staff ss
        JOIN Doctor d ON ss.Staff_AMKA = d.Staff_AMKA
        WHERE ss.Shift_Date = OLD.Shift_Date
          AND ss.Shift_Type = OLD.Shift_Type
          AND ss.Department_Name = OLD.Department_Name
          AND d.`Rank` = 'Ειδικευόμενος'
          AND ss.Staff_AMKA <> OLD.Staff_AMKA;

        IF has_resident > 0 THEN
            
            IF (
                SELECT COUNT(*)
                FROM Shift_Staff ss
                JOIN Doctor d ON ss.Staff_AMKA = d.Staff_AMKA
                WHERE ss.Shift_Date = OLD.Shift_Date
                  AND ss.Shift_Type = OLD.Shift_Type
                  AND ss.Department_Name = OLD.Department_Name
                  AND d.`Rank` IN ('Επιμελητής Α', 'Διευθυντής')
                  AND ss.Staff_AMKA <> OLD.Staff_AMKA
            ) = 0 THEN
                SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'Απαγορεύεται: Δεν μπορεί να αφαιρεθεί ο τελευταίος Επιμελητής Α/Διευθυντής ενώ υπάρχει Ειδικευόμενος στη βάρδια.';
            END IF;
        END IF;
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE TRIGGER `chk_min_staff_on_delete` BEFORE DELETE ON `Shift_Staff` FOR EACH ROW
BEGIN
    DECLARE v_staff_type VARCHAR(45);
    DECLARE v_count_after INT;

    SELECT Staff_Type INTO v_staff_type
    FROM STAFF
    WHERE Staff_AMKA = OLD.Staff_AMKA;

    SELECT COUNT(*) INTO v_count_after
    FROM Shift_Staff ss
    JOIN STAFF s ON ss.Staff_AMKA = s.Staff_AMKA
    WHERE ss.Shift_Date = OLD.Shift_Date
      AND ss.Shift_Type = OLD.Shift_Type
      AND ss.Department_Name = OLD.Department_Name
      AND s.Staff_Type = v_staff_type
      AND ss.Staff_AMKA <> OLD.Staff_AMKA;  

    IF v_staff_type = 'Ιατρός' AND v_count_after < 3 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Απαγορεύεται: Η βάρδια πρέπει να έχει τουλάχιστον 3 ιατρούς.';

    ELSEIF v_staff_type = 'Νοσηλευτής' AND v_count_after < 6 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Απαγορεύεται: Η βάρδια πρέπει να έχει τουλάχιστον 6 νοσηλευτές.';

    ELSEIF v_staff_type = 'Διοικητικός' AND v_count_after < 2 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Απαγορεύεται: Η βάρδια πρέπει να έχει τουλάχιστον 2 διοικητικούς υπαλλήλους.';
    END IF;
END //
DELIMITER ;











SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
